name: Matchday Generator

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  calculate-matchdays:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Debug repo
      run: |
        echo "=== FILE TREE ==="
        find . -type f | sort

    - name: Run generator
      run: python generate_matchdays.py

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        git add matchdays.json

        if git diff --staged --quiet; then
          echo "No changes"
          exit 0
        fi

        git commit -m "🤖 Update matchdays"
        git push
